name: Deploy

on:
  push:
    branches:
    - main

permissions:
      id-token: write
      contents: read    # This is required for actions/checkout

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::323434321179:role/gitOIDC
          role-session-name: samplerolesession
          aws-region: ap-southeast-1
      - name: npm install
        # env:
        #   CI: true
        run: |
          npm install
      - name: deploy
        run: |
          sam build
          sam deploy --no-confirm-changeset
         # zip -j deploy.zip ./*
         # aws lambda update-function-code --function-name=test --zip-file=fileb://deploy.zip
    
  # S3PackageUpload:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Git clone the repository
  #       uses: actions/checkout@v3
  #     - name: configure aws credentials
  #       uses: aws-actions/configure-aws-credentials@v1
  #       with:
  #         role-to-assume: arn:aws:iam::323434321179:role/gitOIDC
  #         role-session-name: samplerolesession
  #         aws-region: ${{ env.AWS_REGION }}
  #     # Upload a file to AWS s3
  #     - name:  Copy index.html to s3
  #       run: |
  #         aws s3 cp ./index.html s3://${{ env.BUCKET_NAME }}/